#!/bin/bash
# بناء المشروع
echo "يُبنى المشروع..."
zola build
 rsync -av --remove-source-files public/* ./
git add .
if [ -z "$1" ]; then
    echo "ما وجدنا رسالتك!"
    git commit -m "لا تعليق"
else
    git commit -m "$1"
fi
echo "رفع التغيرات للفرع الرئيسي"
git push -u origin main
echo "نشرت"

